consumes:
- application/json
definitions:
  GuestbookError:
    description: GuestbookError media type (default view)
    example:
      code: UNAUTHORIZED
      msg: Unauthorized access
    properties:
      code:
        description: Message ID
        example: UNAUTHORIZED
        type: string
      msg:
        description: Localized message
        example: Unauthorized access
        type: string
    required:
    - code
    - msg
    title: 'Mediatype identifier: application/vnd.guestbook.error+json; view=default'
    type: object
  GuestbookGuest:
    description: GuestbookGuest media type (default view)
    example:
      comment: Lorem ipsum
      id: c2d9ecce-f6a3-49cf-8c71-7d4415beb3b8
      timestamp: 1.54398151e+09
    properties:
      comment:
        description: Comment
        example: Lorem ipsum
        type: string
      id:
        description: Guestbook ID
        example: c2d9ecce-f6a3-49cf-8c71-7d4415beb3b8
        type: string
      timestamp:
        description: Entry timestamp
        example: 1.54398151e+09
        format: double
        type: number
    required:
    - id
    - timestamp
    - comment
    title: 'Mediatype identifier: application/vnd.guestbook.guest+json; view=default'
    type: object
  GuestbookGuestCollection:
    description: GuestbookGuestCollection is the media type for an array of GuestbookGuest
      (default view)
    example:
    - comment: Lorem ipsum
      id: c2d9ecce-f6a3-49cf-8c71-7d4415beb3b8
      timestamp: 1.54398151e+09
    - comment: Lorem ipsum
      id: c2d9ecce-f6a3-49cf-8c71-7d4415beb3b8
      timestamp: 1.54398151e+09
    - comment: Lorem ipsum
      id: c2d9ecce-f6a3-49cf-8c71-7d4415beb3b8
      timestamp: 1.54398151e+09
    items:
      $ref: '#/definitions/GuestbookGuest'
    title: 'Mediatype identifier: application/vnd.guestbook.guest+json; type=collection;
      view=default'
    type: array
  GuestbookVersion:
    description: GuestbookVersion media type (default view)
    example:
      git: "000000"
      version: "1.0"
    properties:
      git:
        description: Git commit hash
        example: "000000"
        type: string
      version:
        description: Application version
        example: "1.0"
        type: string
    required:
    - version
    title: 'Mediatype identifier: application/vnd.guestbook.version+json; view=default'
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609066e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609066e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  guestbookType:
    example:
      comment: Lorem ipsum
    properties:
      comment:
        description: Comment
        example: Lorem ipsum
        type: string
    required:
    - comment
    title: guestbookType
    type: object
info:
  description: API for Guest Book
  title: Guest Book API
  version: "1.0"
paths:
  /guestbook/:
    get:
      operationId: guestbook#list
      produces:
      - application/vnd.guestbook.error+json
      - application/vnd.guestbook.guest+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GuestbookGuestCollection'
        "400":
          description: BadRequest is returned if input object is missing required
            attributes or their values are out of range.
          schema:
            $ref: '#/definitions/GuestbookError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GuestbookError'
      schemes:
      - https
      summary: List of guests
      tags:
      - guestbook
    post:
      operationId: guestbook#add
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/guestbookType'
      produces:
      - application/vnd.guestbook.error+json
      responses:
        "204":
          description: No Content
        "400":
          description: BadRequest is returned if input object is missing required
            attributes or their values are out of range.
          schema:
            $ref: '#/definitions/GuestbookError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GuestbookError'
      schemes:
      - https
      summary: Add an entry
      tags:
      - guestbook
  /guestbook/{id}:
    delete:
      operationId: guestbook#delete
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.guestbook.error+json
      responses:
        "204":
          description: No Content
        "400":
          description: BadRequest is returned if input object is missing required
            attributes or their values are out of range.
          schema:
            $ref: '#/definitions/GuestbookError'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/GuestbookError'
      schemes:
      - https
      summary: Delete an entry
      tags:
      - guestbook
  /guestbook/swagger.json:
    get:
      operationId: swagger#/guestbook/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - https
      summary: Download rest/swagger/swagger.json
  /guestbook/version:
    get:
      operationId: version#version
      produces:
      - application/vnd.guestbook.version+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GuestbookVersion'
      schemes:
      - https
      summary: Return application's version and commit hash
      tags:
      - version
produces:
- application/json
responses:
  BadRequest:
    description: BadRequest is returned if input object is missing required attributes
      or their values are out of range.
    schema:
      $ref: '#/definitions/error'
  Forbidden:
    description: Forbidden is returned when user is not authorized to perform an action.
    schema:
      $ref: '#/definitions/error'
  NoContent:
    description: No Content
  NotFound:
    description: Not Found
  Unauthorized:
    description: Unauthorized is returned when user request does not contain authentication
      token or authentication is invalid. The response must include a valid "WWW-Authenticate"
      header.
    headers:
      WWW-Authenticate:
        default: Bearer
        description: https://tools.ietf.org/html/rfc7235
        type: string
    schema:
      $ref: '#/definitions/error'
schemes:
- https
swagger: "2.0"
