// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "guest-book": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/yogihardi/guestbook/rest/design
// --out=$(GOPATH)/src/github.com/yogihardi/guestbook/rest
// --version=v1.3.1

package test
